'use strict';
const CFG=window.SAMARA_CONFIG;
const db=window.supabase.createClient(CFG.supabaseUrl,CFG.supabasePublishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true},global:{headers:{'X-Client-Info':'samara-care-v12'}}});
const rolePages={Admin:['dashboard','patients','beds','care','vitals','medicines','food','billing','employees','reports'],Manager:['dashboard','patients','beds','care','vitals','medicines','food','billing','reports'],Nurse:['dashboard','patients','care','vitals','medicines','food','reports'],Caregiver:['dashboard','patients','care','food'],Accounts:['dashboard','patients','billing','reports'],Kitchen:['dashboard','food']};
const labels={dashboard:'Dashboard',patients:'Patients',beds:'Rooms & Beds',care:'Daily Care',vitals:'Vital Signs',medicines:'Medicines',food:'Food & Diet',billing:'Billing',employees:'Employees',reports:'Reports'};
let me=null,page='dashboard',profiles=[],patients=[],care=[],vitals=[],meds=[],meals=[],billing=[],channel=null;
const $=id=>document.getElementById(id); const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function resolveLoginEmail(login){const id=String(login).trim().toLowerCase();const {data,error}=await db.rpc('samara_login_email',{p_login_id:id});if(error)throw error;if(data)return data;if(id==='admin')return 'admin@users.samaracare.local';throw new Error('Login ID not found. Contact the administrator.')}
function showError(e){alert(e?.message||String(e)||'Unexpected error')}
function setSync(t){$('syncStatus').textContent=t}
async function getProfile(uid){const {data,error}=await db.from('profiles').select('*').eq('id',uid).single();if(error)throw error;if(!data.active)throw new Error('This employee account is inactive.');return data}
async function login(){const btn=$('loginBtn');btn.disabled=true;btn.innerHTML='<span class="spinner"></span> Signing in';try{const login=$('loginId').value.trim(),password=$('loginPassword').value;if(!login||!password)throw new Error('Enter Login ID and password.');const email=await resolveLoginEmail(login);const {data,error}=await db.auth.signInWithPassword({email,password});if(error)throw error;me=await getProfile(data.user.id);await enterApp()}catch(e){await db.auth.signOut();showError(e)}finally{btn.disabled=false;btn.textContent='Sign in'}}
async function enterApp(){$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('userName').textContent=me.full_name;$('userRole').textContent=me.role;$('avatar').textContent=me.full_name?.[0]||'U';buildNav();await loadAll();subscribeRealtime();go('dashboard')}
function buildNav(){$('nav').innerHTML=(rolePages[me.role]||['dashboard']).map(p=>`<button id="nav-${p}" data-page="${p}"><span>${labels[p]}</span></button>`).join('');$('nav').querySelectorAll('button').forEach(b=>b.onclick=()=>go(b.dataset.page))}
async function loadAll(){setSync('Syncing…');const queries=[db.from('profiles').select('*').order('full_name'),db.from('patients').select('*').order('created_at',{ascending:false}),db.from('care_records').select('*').order('recorded_at',{ascending:false}).limit(100),db.from('vital_signs').select('*').order('recorded_at',{ascending:false}).limit(100),db.from('medicine_records').select('*').order('created_at',{ascending:false}).limit(100),db.from('meal_records').select('*').order('recorded_at',{ascending:false}).limit(100)];if(['Admin','Manager','Accounts'].includes(me.role))queries.push(db.from('billing_transactions').select('*').order('recorded_at',{ascending:false}).limit(200));const res=await Promise.all(queries);const err=res.find(x=>x.error)?.error;if(err)throw err;[profiles,patients,care,vitals,meds,meals]=res.slice(0,6).map(x=>x.data||[]);billing=res[6]?.data||[];setSync('Live')}
function subscribeRealtime(){if(channel)db.removeChannel(channel);channel=db.channel('samara-live-v12').on('postgres_changes',{event:'*',schema:'public'},async()=>{try{await loadAll();render()}catch(e){console.error(e)}}).subscribe()}
function closeMobileMenu(){document.getElementById('sidebar')?.classList.remove('open');document.getElementById('navOverlay')?.classList.remove('show');document.body.classList.remove('menu-open')}
function toggleMobileMenu(){const open=document.getElementById('sidebar')?.classList.toggle('open');document.getElementById('navOverlay')?.classList.toggle('show',!!open);document.body.classList.toggle('menu-open',!!open)}
function go(p){closeMobileMenu();page=p;document.querySelectorAll('.nav button').forEach(b=>b.classList.remove('active'));$(`nav-${p}`)?.classList.add('active');$('pageTitle').textContent=labels[p];render()}
function render(){const fn=window[`render_${page}`];$('content').innerHTML=fn?fn():'';bindPageActions()}
function pname(id){return patients.find(p=>p.id===id)?.full_name||'Unknown patient'}function staffName(id){return profiles.find(p=>p.id===id)?.full_name||'—'}
function metric(label,value,sub,cls=''){return `<div class="card metric"><div class="label">${esc(label)}</div><div class="value ${cls}">${esc(value)}</div><div class="muted" style="font-size:12px">${esc(sub)}</div></div>`}
function render_dashboard(){const occupied=patients.filter(x=>x.status==='Active').length,pending=meds.filter(x=>x.status==='Pending').length,critical=vitals.filter(x=>x.alert_level==='Critical').length,outstanding=patients.reduce((a,p)=>a+Number(p.outstanding||0),0);return `<div class="page-head"><div><h2>Dashboard</h2><div class="muted">Real-time Assisted Living overview</div></div></div><div class="cards">${metric('Total Beds','25','Facility capacity')}${metric('Occupied',occupied,`${25-occupied} available`,'ok')}${metric('Medicines Due',pending,'Pending doses',pending?'warn':'ok')}${metric('Outstanding',`₹${outstanding.toLocaleString('en-IN')}`,'Current receivables','bad')}</div><div class="grid2"><div class="card"><h3>Clinical alerts</h3><div class="list"><div class="list-item"><span>Critical vital readings</span><span class="tag ${critical?'red':'green'}">${critical}</span></div><div class="list-item"><span>Pending medicines</span><span class="tag ${pending?'amber':'green'}">${pending}</span></div><div class="list-item"><span>Care records today</span><span class="tag">${care.filter(x=>new Date(x.recorded_at).toDateString()===new Date().toDateString()).length}</span></div></div></div><div class="card"><h3>Recent activity</h3><div class="list">${[...care.slice(0,3),...vitals.slice(0,3)].sort((a,b)=>new Date(b.recorded_at)-new Date(a.recorded_at)).slice(0,5).map(x=>`<div class="list-item"><span><b>${esc(pname(x.patient_id))}</b><br><small class="muted">${esc(x.activity||`BP ${x.blood_pressure||'-'}, SpO₂ ${x.spo2||'-'}%`)}</small></span><small>${new Date(x.recorded_at).toLocaleString('en-IN')}</small></div>`).join('')||'<div class="muted">No activity yet</div>'}</div></div></div>`}
function render_patients(){return `<div class="page-head"><div><h2>Patients</h2><div class="muted">Shared resident records</div></div>${['Admin','Manager','Nurse'].includes(me.role)?'<button class="btn btn-primary" id="addPatient">+ Add Patient</button>':''}</div><div class="table-wrap"><table><thead><tr><th>Code</th><th>Patient</th><th>Room</th><th>Diagnosis</th><th>Care</th><th>Outstanding</th></tr></thead><tbody>${patients.map(p=>`<tr><td>${esc(p.patient_code)}</td><td><b>${esc(p.full_name)}</b><br><small>${esc(p.age||'')} ${p.gender?'· '+esc(p.gender):''}</small></td><td>${esc(p.room_bed||'-')}</td><td>${esc(p.diagnosis||'-')}</td><td><span class="tag">${esc(p.care_level||'-')}</span></td><td>₹${Number(p.outstanding||0).toLocaleString('en-IN')}</td></tr>`).join('')||'<tr><td colspan="6">No patients yet</td></tr>'}</tbody></table></div>`}
function render_beds(){let html='';for(let i=1;i<=25;i++){const room=`${100+Math.ceil(i/2)}-${i%2?'A':'B'}`,p=patients.find(x=>x.room_bed===room&&x.status==='Active');html+=`<div class="bed ${p?'occupied':''}"><b>${room}</b><div class="muted" style="margin-top:6px">${p?esc(p.full_name):'Available'}</div></div>`}return `<div class="page-head"><div><h2>Rooms & Beds</h2><div class="muted">Live occupancy map</div></div></div><div class="bed-grid">${html}</div>`}
function modulePage(title,sub,buttonId,buttonLabel,heads,rows){return `<div class="page-head"><div><h2>${title}</h2><div class="muted">${sub}</div></div>${buttonId?`<button class="btn btn-primary" id="${buttonId}">+ ${buttonLabel}</button>`:''}</div><div class="table-wrap"><table><thead><tr>${heads.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows||`<tr><td colspan="${heads.length}">No records yet</td></tr>`}</tbody></table></div>`}
function render_care(){return modulePage('Daily Care','Hygiene, mobility, feeding and assistance','addCare','Record Care',['Patient','Activity','Status','Employee','Time'],care.map(x=>`<tr><td>${esc(pname(x.patient_id))}</td><td>${esc(x.activity)}</td><td><span class="tag">${esc(x.status)}</span></td><td>${esc(staffName(x.recorded_by))}</td><td>${new Date(x.recorded_at).toLocaleString('en-IN')}</td></tr>`).join(''))}
function render_vitals(){return modulePage('Vital Signs','Clinical readings and automatic oxygen alert',['Admin','Manager','Nurse'].includes(me.role)?'addVitals':'','Record Vitals',['Patient','BP','SpO₂','Temperature','Alert','Time'],vitals.map(x=>`<tr><td>${esc(pname(x.patient_id))}</td><td>${esc(x.blood_pressure||'-')}</td><td>${esc(x.spo2||'-')}%</td><td>${esc(x.temperature||'-')}°F</td><td><span class="tag ${x.alert_level==='Critical'?'red':'green'}">${esc(x.alert_level)}</span></td><td>${new Date(x.recorded_at).toLocaleString('en-IN')}</td></tr>`).join(''))}
function render_medicines(){return modulePage('Medicines','Medication schedule and administration',['Admin','Manager','Nurse'].includes(me.role)?'addMedicine':'','Add Medicine',['Patient','Medicine','Time','Status','Action'],meds.map(x=>`<tr><td>${esc(pname(x.patient_id))}</td><td>${esc(x.medicine)}</td><td>${esc(x.scheduled_time||'-')}</td><td><span class="tag ${x.status==='Given'?'green':x.status==='Pending'?'amber':'red'}">${esc(x.status)}</span></td><td>${x.status==='Pending'&&['Admin','Manager','Nurse'].includes(me.role)?`<button class="btn btn-secondary btn-small med-given" data-id="${x.id}">Mark Given</button>`:''}</td></tr>`).join(''))}
function render_food(){return modulePage('Food & Diet','Meal plan and consumption','addMeal','Record Meal',['Patient','Meal','Diet','Consumption','Employee'],meals.map(x=>`<tr><td>${esc(pname(x.patient_id))}</td><td>${esc(x.meal_type)}</td><td>${esc(x.diet_type||'-')}</td><td>${esc(x.consumption||'-')}</td><td>${esc(staffName(x.recorded_by))}</td></tr>`).join(''))}
function render_billing(){if(!['Admin','Manager','Accounts'].includes(me.role))return '<div class="notice">You do not have access to billing.</div>';return modulePage('Billing','Charges, payments and outstanding','addBilling','Add Transaction',['Patient','Type','Amount','Description','Employee','Time'],billing.map(x=>`<tr><td>${esc(pname(x.patient_id))}</td><td>${esc(x.transaction_type)}</td><td>₹${Number(x.amount).toLocaleString('en-IN')}</td><td>${esc(x.description||'-')}</td><td>${esc(staffName(x.recorded_by))}</td><td>${new Date(x.recorded_at).toLocaleString('en-IN')}</td></tr>`).join(''))}
function render_employees(){return `<div class="page-head"><div><h2>Employees</h2><div class="muted">Central login accounts—no Edge Function required</div></div><button class="btn btn-primary" id="addEmployee">+ Add Employee</button></div><div class="notice"><b>Admin-controlled accounts:</b> New users can sign in from any authorised phone or computer after creation.</div><div class="table-wrap"><table><thead><tr><th>Name</th><th>Employee ID</th><th>Role</th><th>Login ID</th><th>Email</th><th>Mobile</th><th>Status</th><th>Action</th></tr></thead><tbody>${profiles.map(p=>`<tr><td>${esc(p.full_name)}</td><td>${esc(p.employee_id||'-')}</td><td>${esc(p.role)}</td><td><code>${esc(p.login_id)}</code></td><td>${esc(p.auth_email||'-')}</td><td>${esc(p.mobile||'-')}</td><td><span class="tag ${p.active?'green':'red'}">${p.active?'Active':'Inactive'}</span></td><td>${p.id!==me.id?`<button class="btn ${p.active?'btn-danger':'btn-secondary'} btn-small toggle-employee" data-id="${p.id}" data-active="${!p.active}">${p.active?'Disable':'Activate'}</button>`:''}</td></tr>`).join('')}</tbody></table></div>`}
function render_reports(){const outstanding=patients.reduce((a,p)=>a+Number(p.outstanding||0),0);return `<div class="page-head"><div><h2>Reports</h2><div class="muted">Current operational summary</div></div><button class="btn btn-primary" onclick="window.print()">Print</button></div><div class="cards">${metric('Active Patients',patients.filter(x=>x.status==='Active').length,'Current census')}${metric('Care Records',care.length,'Recent loaded records')}${metric('Medicine Compliance',meds.length?`${Math.round(meds.filter(x=>x.status==='Given').length/meds.length*100)}%`:'0%','Given doses','ok')}${metric('Outstanding',`₹${outstanding.toLocaleString('en-IN')}`,'Patient balance','bad')}</div>`}
function patientOptions(){return patients.filter(x=>x.status==='Active').map(p=>`<option value="${p.id}">${esc(p.full_name)} · ${esc(p.room_bed||'-')}</option>`).join('')}
function modal(html){$('modalRoot').innerHTML=`<div class="modal"><div class="modal-card">${html}</div></div>`;document.querySelector('.close')?.addEventListener('click',closeModal)}function closeModal(){$('modalRoot').innerHTML=''}
function field(label,id,type='text',value=''){return `<div class="field"><label>${label}</label><input id="${id}" type="${type}" value="${esc(value)}"></div>`}function select(label,id,values){return `<div class="field"><label>${label}</label><select id="${id}">${values.map(v=>`<option>${esc(v)}</option>`).join('')}</select></div>`}function patientSelect(id){return `<div class="field"><label>Patient</label><select id="${id}">${patientOptions()}</select></div>`}
function openPatient(){modal(`<div class="modal-head"><h3>Add Patient</h3><button class="close">×</button></div><div class="form-grid">${field('Full Name','p_name')}${field('Age','p_age','number')}${select('Gender','p_gender',['Male','Female','Other'])}${field('Room / Bed','p_room')}${field('Admission Date','p_date','date')}<div class="field"><label>Care Level</label><select id="p_care"><option>Independent</option><option selected>Assisted</option><option>High Dependency</option></select></div><div class="field full"><label>Diagnosis</label><textarea id="p_diag"></textarea></div>${field('Emergency Contact','p_contact')}<div class="full right"><button class="btn btn-primary" id="savePatient">Save Patient</button></div></div>`);$('savePatient').onclick=savePatient}
async function savePatient(){try{const code=`P${String(patients.length+1).padStart(4,'0')}`;const {error}=await db.from('patients').insert({patient_code:code,full_name:$('p_name').value.trim(),age:Number($('p_age').value)||null,gender:$('p_gender').value,room_bed:$('p_room').value.trim(),admission_date:$('p_date').value||null,diagnosis:$('p_diag').value.trim(),emergency_contact:$('p_contact').value.trim(),care_level:$('p_care').value,created_by:me.id});if(error)throw error;closeModal()}catch(e){showError(e)}}
function openSimple(kind){const forms={care:`${patientSelect('x_patient')}${select('Activity','x_a',['Oral Care','Bathing','Dress Change','Diaper Change','Feeding Assistance','Toileting','Position Change','Walking Support'])}${select('Status','x_s',['Completed','Pending','Patient Refused','Not Applicable'])}${field('Remarks','x_r')}`,vitals:`${patientSelect('x_patient')}${field('Blood Pressure','x_bp')}${field('SpO₂ (%)','x_spo','number')}${field('Temperature °F','x_temp','number')}`,medicine:`${patientSelect('x_patient')}${field('Medicine','x_med')}${field('Scheduled Time','x_time','time')}${select('Status','x_s',['Pending','Given','Refused','Withheld'])}`,meal:`${patientSelect('x_patient')}${select('Meal','x_meal',['Breakfast','Lunch','Evening Snack','Dinner'])}${select('Diet','x_diet',['Normal','Diabetic','Soft','Liquid','Renal','High Protein'])}${select('Consumption','x_cons',['Fully Consumed','Partially Consumed','Refused','Not Served'])}`,billing:`${patientSelect('x_patient')}${select('Type','x_type',['Charge','Payment'])}${field('Amount (₹)','x_amount','number')}${field('Description','x_desc')}`};modal(`<div class="modal-head"><h3>New Entry</h3><button class="close">×</button></div><div class="form-grid">${forms[kind]}<div class="full right"><button class="btn btn-primary" id="saveSimple">Save</button></div></div>`);$('saveSimple').onclick=()=>saveSimple(kind)}
async function saveSimple(k){try{let table,obj;if(k==='care'){table='care_records';obj={patient_id:$('x_patient').value,activity:$('x_a').value,status:$('x_s').value,remarks:$('x_r').value,recorded_by:me.id}}if(k==='vitals'){const spo=Number($('x_spo').value);table='vital_signs';obj={patient_id:$('x_patient').value,blood_pressure:$('x_bp').value,spo2:spo||null,temperature:Number($('x_temp').value)||null,alert_level:spo&&spo<92?'Critical':'Normal',recorded_by:me.id}}if(k==='medicine'){table='medicine_records';obj={patient_id:$('x_patient').value,medicine:$('x_med').value,scheduled_time:$('x_time').value||null,status:$('x_s').value,recorded_by:me.id}}if(k==='meal'){table='meal_records';obj={patient_id:$('x_patient').value,meal_type:$('x_meal').value,diet_type:$('x_diet').value,consumption:$('x_cons').value,recorded_by:me.id}}if(k==='billing'){table='billing_transactions';obj={patient_id:$('x_patient').value,transaction_type:$('x_type').value,amount:Number($('x_amount').value),description:$('x_desc').value,recorded_by:me.id}}const {error}=await db.from(table).insert(obj);if(error)throw error;if(k==='billing'){const p=patients.find(x=>x.id===obj.patient_id);const newOutstanding=Math.max(0,Number(p.outstanding||0)+(obj.transaction_type==='Charge'?obj.amount:-obj.amount));const {error:pe}=await db.from('patients').update({outstanding:newOutstanding}).eq('id',p.id);if(pe)throw pe}closeModal()}catch(e){showError(e)}}
function openEmployee(){modal(`<div class="modal-head"><h3>Create Employee</h3><button class="close">×</button></div><div class="form-grid">${field('Name','e_name')}${field('Employee ID','e_emp')}${field('Mobile','e_mobile')}${select('Role','e_role',['Admin','Manager','Nurse','Caregiver','Accounts','Kitchen'])}${field('Login ID','e_login')}${field('Employee Email','e_email','email')}${field('Temporary Password','e_password','password')}<div class="full notice"><b>Login:</b> The employee will sign in using the Login ID. The email is used securely by Supabase for authentication and password recovery.</div><div class="full right"><button class="btn btn-primary" id="createEmployee">Create</button></div></div>`);$('createEmployee').onclick=createEmployee}
async function createEmployee(){const btn=$('createEmployee');btn.disabled=true;btn.textContent='Creating…';let tempClient;try{const login=$('e_login').value.trim().toLowerCase(),email=$('e_email').value.trim().toLowerCase(),password=$('e_password').value,name=$('e_name').value.trim();if(!login||!email||!password||!name)throw new Error('Name, Login ID, employee email and password are required.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error('Enter a valid employee email address.');if(password.length<6)throw new Error('Password must contain at least 6 characters.');if(profiles.some(x=>x.login_id===login))throw new Error('That Login ID already exists.');if(profiles.some(x=>String(x.auth_email||'').toLowerCase()===email))throw new Error('That email address is already assigned to an employee.');tempClient=window.supabase.createClient(CFG.supabaseUrl,CFG.supabasePublishableKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false,storageKey:`samara-create-${Date.now()}`}});const {data,error}=await tempClient.auth.signUp({email,password,options:{data:{login_id:login,full_name:name}}});if(error)throw error;if(!data.user)throw new Error('Supabase did not create the employee account. Confirm that Email provider is enabled and Confirm email is disabled.');const {error:rpcError}=await db.rpc('samara_admin_save_employee',{p_user_id:data.user.id,p_login_id:login,p_auth_email:email,p_full_name:name,p_role:$('e_role').value,p_employee_id:$('e_emp').value,p_mobile:$('e_mobile').value,p_active:true});if(rpcError)throw rpcError;await tempClient.auth.signOut();closeModal();await loadAll();render();alert('Employee created successfully. The employee can sign in using the Login ID from any authorised device.')}catch(e){showError(e)}finally{btn.disabled=false;btn.textContent='Create'}}
async function toggleEmployee(id,active){try{const {error}=await db.rpc('samara_admin_set_employee_active',{p_user_id:id,p_active:active});if(error)throw error;await loadAll();render()}catch(e){showError(e)}}
function bindPageActions(){$('addPatient')?.addEventListener('click',openPatient);$('addCare')?.addEventListener('click',()=>openSimple('care'));$('addVitals')?.addEventListener('click',()=>openSimple('vitals'));$('addMedicine')?.addEventListener('click',()=>openSimple('medicine'));$('addMeal')?.addEventListener('click',()=>openSimple('meal'));$('addBilling')?.addEventListener('click',()=>openSimple('billing'));$('addEmployee')?.addEventListener('click',openEmployee);document.querySelectorAll('.toggle-employee').forEach(b=>b.onclick=()=>toggleEmployee(b.dataset.id,b.dataset.active==='true'));document.querySelectorAll('.med-given').forEach(b=>b.onclick=async()=>{const {error}=await db.from('medicine_records').update({status:'Given',administered_at:new Date().toISOString()}).eq('id',b.dataset.id);if(error)showError(error)})}
async function changePassword(){const pw=prompt('Enter new password (minimum 6 characters):');if(!pw)return;if(pw.length<6)return alert('Password must contain at least 6 characters.');const {error}=await db.auth.updateUser({password:pw});if(error)showError(error);else alert('Password changed successfully.')}
async function logout(){if(channel)await db.removeChannel(channel);await db.auth.signOut();location.reload()}
$('loginBtn').onclick=login;$('loginPassword').onkeydown=e=>{if(e.key==='Enter')login()};$('logoutBtn').onclick=logout;$('passwordBtn').onclick=changePassword;$('mobileMenuBtn').onclick=toggleMobileMenu;$('navOverlay').onclick=closeMobileMenu;window.addEventListener('resize',()=>{if(window.innerWidth>700)closeMobileMenu()});
(async()=>{try{const {data}=await db.auth.getSession();if(data.session){me=await getProfile(data.session.user.id);await enterApp()}}catch(e){console.error(e);await db.auth.signOut()}})();

